#!/bin/bash

# Start the nginx service
service nginx start

# Set the envionment variables to defaults if not present
if [ -z $OVERVIEWER_CYCLE ]; then
	export OVERVIEWER_CYCLE=3600
fi

if [ -z $OVERVIEWER_WORLD_NAME ]; then
	export OVERVIEWER_WORLD_NAME="myworld"
fi

# Repeatedly render the maps at the specified interval
while true; do
	/usr/src/app/overviewer/overviewer.py --config="/ov/config/config.py" --genpoi
	/usr/src/app/overviewer/overviewer.py --config="/ov/config/config.py"
	sleep $OVERVIEWER_CYCLE
done
